name: Build General APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3-dev openjdk-17-jdk libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33
      - name: Build APK
        run: |
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          yes | buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Predator-General-APK
          path: bin/*.apk
          
